spring:
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username:  test
    password:  test

#    test-on-borrow: true
#    validationQuery: SELECT 1 FROM DUAL

logging:
    level:
        org.springframework.*: 'DEBUG'